[package]
name = "toy-trx"
version = "0.1.0"
edition = "2021"

[lib]
name = "toy_trx"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.55"
csv = "1.1"
rust_decimal = "1.22.0"
rust_decimal_macros = "1.22.0"